services:
  go-service:
    build: ./service1
    container_name: service1
    ports:
      - "9090:9090"
    networks:
      - jenkins_docker_jenkins-net

  python-service:
    build: ./service2
    container_name: service2
    ports:
      - "5000:5000"
    networks:
      - jenkins_docker_jenkins-net

networks:
  jenkins_docker_jenkins-net:
    external: true
